name: salary-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.10
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - pip:
    - streamlit==1.58.0
